rowApp_Tab_RaceResults <-
  tabItem(
    tabName = "raceResults",
    fluidRow(
      column(
        4,
        style = "background-color:#CDF7D9;",
        h3("Find results for a specific crew:"),
        selectInput("rr_Gender","Crew Gender:",
                    list("Male",
                         "Female",
                         "Mixed")),
        selectInput("rr_BoatType","Boat Type:",
                    list("Single",
                         "Double",
                         "Quad",
                         "Coxed Quad",
                         "Octuple",
                         "Pair",
                         "Coxed Pair",
                         "Four",
                         "Coxed Four",
                         "Eight")),
        "If you leave this club name filter as 'All' then it will find all results for the gender and boat type you requested.",
        textInput("rr_ClubName","Club Name:",
                  value = 'All'),
        br(),
        br(),
        br(),
        paste("For more information or assistance email",
              emailAddress,
              sep = " "),
        br(),
        br(),
        br()
      ),
      column(
        4,
        h3("Specifc crew Results:"),
        dataTableOutput("rr_FilteredRaceResults")
      ),
      column(
        4,
        style = "background-color:#CDF7D9;",
        h3(" All Race Result Links"),
        br(),
        br(),
        h4("2018 Results"),
        br(),
        downloadButton("HORR2018.xlsx", "HORR"),
        br(),
        downloadButton("HOR42018.xlsx", "Fours Head"),
        br(),
        downloadButton("PairsHead2018.xlsx","Pairs Head"),
        br(),
        downloadButton("ScullersHead2018.xlsx","Scullers Head"),
        br(),
        downloadButton("SHORR2018.xlsx","Schools Head"),
        br(),
        downloadButton("HeadOfTheTrent.xlsx","Head of the Trent"),
        br(),
        br(),
        br()
      )
    )
  )